/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DataMarketRouteImport } from './routes/data-market'
import { Route as CpRouteImport } from './routes/cp'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as CpIndexRouteImport } from './routes/cp.index'
import { Route as WorkflowsNewRouteImport } from './routes/workflows/new'
import { Route as WorkflowsRunIdRouteImport } from './routes/workflows/$runId'
import { Route as SoftwareScriptsRouteImport } from './routes/software.scripts'
import { Route as JobsJobIdRouteImport } from './routes/jobs_.$jobId'
import { Route as CpUsersRouteImport } from './routes/cp.users'
import { Route as CpSoftwareRouteImport } from './routes/cp.software'
import { Route as CpQueuesRouteImport } from './routes/cp.queues'
import { Route as CpMeteringRouteImport } from './routes/cp.metering'
import { Route as CpInfrastructureRouteImport } from './routes/cp.infrastructure'
import { Route as CpDataRouteImport } from './routes/cp.data'
import { Route as CpAuditRouteImport } from './routes/cp.audit'
import { Route as CpAgentsRouteImport } from './routes/cp.agents'
import { Route as CpAgentRegistrationRouteImport } from './routes/cp.agent-registration'
import { Route as CpAccountsRouteImport } from './routes/cp.accounts'
import { Route as SoftwareWorkflowTemplatesNewRouteImport } from './routes/software.workflow-templates.new'
import { Route as SoftwareWorkflowTemplatesTemplateIdRouteImport } from './routes/software.workflow-templates.$templateId'
import { Route as SoftwareUsecasesNewRouteImport } from './routes/software.usecases.new'
import { Route as SoftwareUsecasesUsecaseIdRouteImport } from './routes/software.usecases.$usecaseId'
import { Route as SoftwareSpackNewRouteImport } from './routes/software.spack.new'
import { Route as SoftwareScriptsNewRouteImport } from './routes/software.scripts.new'
import { Route as SoftwareScriptsScriptIdRouteImport } from './routes/software.scripts.$scriptId'
import { Route as AgentsAgentIdSshRouteImport } from './routes/agents.$agentId.ssh'
import { Route as AgentsAgentIdSoftwareRouteImport } from './routes/agents.$agentId.software'
import { Route as SoftwareSpackSourceNameRouteImport } from './routes/software.spack.$source.$name'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMarketRoute = DataMarketRouteImport.update({
  id: '/data-market',
  path: '/data-market',
  getParentRoute: () => rootRouteImport,
} as any)
const CpRoute = CpRouteImport.update({
  id: '/cp',
  path: '/cp',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const CpIndexRoute = CpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CpRoute,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRunIdRoute = WorkflowsRunIdRouteImport.update({
  id: '/workflows/$runId',
  path: '/workflows/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareScriptsRoute = SoftwareScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => SoftwareRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CpUsersRoute = CpUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CpRoute,
} as any)
const CpSoftwareRoute = CpSoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => CpRoute,
} as any)
const CpQueuesRoute = CpQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => CpRoute,
} as any)
const CpMeteringRoute = CpMeteringRouteImport.update({
  id: '/metering',
  path: '/metering',
  getParentRoute: () => CpRoute,
} as any)
const CpInfrastructureRoute = CpInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => CpRoute,
} as any)
const CpDataRoute = CpDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => CpRoute,
} as any)
const CpAuditRoute = CpAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => CpRoute,
} as any)
const CpAgentsRoute = CpAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => CpRoute,
} as any)
const CpAgentRegistrationRoute = CpAgentRegistrationRouteImport.update({
  id: '/agent-registration',
  path: '/agent-registration',
  getParentRoute: () => CpRoute,
} as any)
const CpAccountsRoute = CpAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => CpRoute,
} as any)
const SoftwareWorkflowTemplatesNewRoute =
  SoftwareWorkflowTemplatesNewRouteImport.update({
    id: '/workflow-templates/new',
    path: '/workflow-templates/new',
    getParentRoute: () => SoftwareRoute,
  } as any)
const SoftwareWorkflowTemplatesTemplateIdRoute =
  SoftwareWorkflowTemplatesTemplateIdRouteImport.update({
    id: '/workflow-templates/$templateId',
    path: '/workflow-templates/$templateId',
    getParentRoute: () => SoftwareRoute,
  } as any)
const SoftwareUsecasesNewRoute = SoftwareUsecasesNewRouteImport.update({
  id: '/usecases/new',
  path: '/usecases/new',
  getParentRoute: () => SoftwareRoute,
} as any)
const SoftwareUsecasesUsecaseIdRoute =
  SoftwareUsecasesUsecaseIdRouteImport.update({
    id: '/usecases/$usecaseId',
    path: '/usecases/$usecaseId',
    getParentRoute: () => SoftwareRoute,
  } as any)
const SoftwareSpackNewRoute = SoftwareSpackNewRouteImport.update({
  id: '/spack/new',
  path: '/spack/new',
  getParentRoute: () => SoftwareRoute,
} as any)
const SoftwareScriptsNewRoute = SoftwareScriptsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SoftwareScriptsRoute,
} as any)
const SoftwareScriptsScriptIdRoute = SoftwareScriptsScriptIdRouteImport.update({
  id: '/$scriptId',
  path: '/$scriptId',
  getParentRoute: () => SoftwareScriptsRoute,
} as any)
const AgentsAgentIdSshRoute = AgentsAgentIdSshRouteImport.update({
  id: '/$agentId/ssh',
  path: '/$agentId/ssh',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAgentIdSoftwareRoute = AgentsAgentIdSoftwareRouteImport.update({
  id: '/$agentId/software',
  path: '/$agentId/software',
  getParentRoute: () => AgentsRoute,
} as any)
const SoftwareSpackSourceNameRoute = SoftwareSpackSourceNameRouteImport.update({
  id: '/spack/$source/$name',
  path: '/spack/$source/$name',
  getParentRoute: () => SoftwareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/cp': typeof CpRouteWithChildren
  '/data-market': typeof DataMarketRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/software': typeof SoftwareRouteWithChildren
  '/terminal': typeof TerminalRoute
  '/cp/accounts': typeof CpAccountsRoute
  '/cp/agent-registration': typeof CpAgentRegistrationRoute
  '/cp/agents': typeof CpAgentsRoute
  '/cp/audit': typeof CpAuditRoute
  '/cp/data': typeof CpDataRoute
  '/cp/infrastructure': typeof CpInfrastructureRoute
  '/cp/metering': typeof CpMeteringRoute
  '/cp/queues': typeof CpQueuesRoute
  '/cp/software': typeof CpSoftwareRoute
  '/cp/users': typeof CpUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/software/scripts': typeof SoftwareScriptsRouteWithChildren
  '/workflows/$runId': typeof WorkflowsRunIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/cp/': typeof CpIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/agents/$agentId/software': typeof AgentsAgentIdSoftwareRoute
  '/agents/$agentId/ssh': typeof AgentsAgentIdSshRoute
  '/software/scripts/$scriptId': typeof SoftwareScriptsScriptIdRoute
  '/software/scripts/new': typeof SoftwareScriptsNewRoute
  '/software/spack/new': typeof SoftwareSpackNewRoute
  '/software/usecases/$usecaseId': typeof SoftwareUsecasesUsecaseIdRoute
  '/software/usecases/new': typeof SoftwareUsecasesNewRoute
  '/software/workflow-templates/$templateId': typeof SoftwareWorkflowTemplatesTemplateIdRoute
  '/software/workflow-templates/new': typeof SoftwareWorkflowTemplatesNewRoute
  '/software/spack/$source/$name': typeof SoftwareSpackSourceNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/data-market': typeof DataMarketRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/software': typeof SoftwareRouteWithChildren
  '/terminal': typeof TerminalRoute
  '/cp/accounts': typeof CpAccountsRoute
  '/cp/agent-registration': typeof CpAgentRegistrationRoute
  '/cp/agents': typeof CpAgentsRoute
  '/cp/audit': typeof CpAuditRoute
  '/cp/data': typeof CpDataRoute
  '/cp/infrastructure': typeof CpInfrastructureRoute
  '/cp/metering': typeof CpMeteringRoute
  '/cp/queues': typeof CpQueuesRoute
  '/cp/software': typeof CpSoftwareRoute
  '/cp/users': typeof CpUsersRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/software/scripts': typeof SoftwareScriptsRouteWithChildren
  '/workflows/$runId': typeof WorkflowsRunIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/cp': typeof CpIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/agents/$agentId/software': typeof AgentsAgentIdSoftwareRoute
  '/agents/$agentId/ssh': typeof AgentsAgentIdSshRoute
  '/software/scripts/$scriptId': typeof SoftwareScriptsScriptIdRoute
  '/software/scripts/new': typeof SoftwareScriptsNewRoute
  '/software/spack/new': typeof SoftwareSpackNewRoute
  '/software/usecases/$usecaseId': typeof SoftwareUsecasesUsecaseIdRoute
  '/software/usecases/new': typeof SoftwareUsecasesNewRoute
  '/software/workflow-templates/$templateId': typeof SoftwareWorkflowTemplatesTemplateIdRoute
  '/software/workflow-templates/new': typeof SoftwareWorkflowTemplatesNewRoute
  '/software/spack/$source/$name': typeof SoftwareSpackSourceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/cp': typeof CpRouteWithChildren
  '/data-market': typeof DataMarketRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/settings': typeof SettingsRoute
  '/software': typeof SoftwareRouteWithChildren
  '/terminal': typeof TerminalRoute
  '/cp/accounts': typeof CpAccountsRoute
  '/cp/agent-registration': typeof CpAgentRegistrationRoute
  '/cp/agents': typeof CpAgentsRoute
  '/cp/audit': typeof CpAuditRoute
  '/cp/data': typeof CpDataRoute
  '/cp/infrastructure': typeof CpInfrastructureRoute
  '/cp/metering': typeof CpMeteringRoute
  '/cp/queues': typeof CpQueuesRoute
  '/cp/software': typeof CpSoftwareRoute
  '/cp/users': typeof CpUsersRoute
  '/jobs_/$jobId': typeof JobsJobIdRoute
  '/software/scripts': typeof SoftwareScriptsRouteWithChildren
  '/workflows/$runId': typeof WorkflowsRunIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
  '/cp/': typeof CpIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/agents/$agentId/software': typeof AgentsAgentIdSoftwareRoute
  '/agents/$agentId/ssh': typeof AgentsAgentIdSshRoute
  '/software/scripts/$scriptId': typeof SoftwareScriptsScriptIdRoute
  '/software/scripts/new': typeof SoftwareScriptsNewRoute
  '/software/spack/new': typeof SoftwareSpackNewRoute
  '/software/usecases/$usecaseId': typeof SoftwareUsecasesUsecaseIdRoute
  '/software/usecases/new': typeof SoftwareUsecasesNewRoute
  '/software/workflow-templates/$templateId': typeof SoftwareWorkflowTemplatesTemplateIdRoute
  '/software/workflow-templates/new': typeof SoftwareWorkflowTemplatesNewRoute
  '/software/spack/$source/$name': typeof SoftwareSpackSourceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/cp'
    | '/data-market'
    | '/files'
    | '/jobs'
    | '/login'
    | '/operations'
    | '/settings'
    | '/software'
    | '/terminal'
    | '/cp/accounts'
    | '/cp/agent-registration'
    | '/cp/agents'
    | '/cp/audit'
    | '/cp/data'
    | '/cp/infrastructure'
    | '/cp/metering'
    | '/cp/queues'
    | '/cp/software'
    | '/cp/users'
    | '/jobs/$jobId'
    | '/software/scripts'
    | '/workflows/$runId'
    | '/workflows/new'
    | '/cp/'
    | '/workflows/'
    | '/agents/$agentId/software'
    | '/agents/$agentId/ssh'
    | '/software/scripts/$scriptId'
    | '/software/scripts/new'
    | '/software/spack/new'
    | '/software/usecases/$usecaseId'
    | '/software/usecases/new'
    | '/software/workflow-templates/$templateId'
    | '/software/workflow-templates/new'
    | '/software/spack/$source/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/data-market'
    | '/files'
    | '/jobs'
    | '/login'
    | '/operations'
    | '/settings'
    | '/software'
    | '/terminal'
    | '/cp/accounts'
    | '/cp/agent-registration'
    | '/cp/agents'
    | '/cp/audit'
    | '/cp/data'
    | '/cp/infrastructure'
    | '/cp/metering'
    | '/cp/queues'
    | '/cp/software'
    | '/cp/users'
    | '/jobs/$jobId'
    | '/software/scripts'
    | '/workflows/$runId'
    | '/workflows/new'
    | '/cp'
    | '/workflows'
    | '/agents/$agentId/software'
    | '/agents/$agentId/ssh'
    | '/software/scripts/$scriptId'
    | '/software/scripts/new'
    | '/software/spack/new'
    | '/software/usecases/$usecaseId'
    | '/software/usecases/new'
    | '/software/workflow-templates/$templateId'
    | '/software/workflow-templates/new'
    | '/software/spack/$source/$name'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/cp'
    | '/data-market'
    | '/files'
    | '/jobs'
    | '/login'
    | '/operations'
    | '/settings'
    | '/software'
    | '/terminal'
    | '/cp/accounts'
    | '/cp/agent-registration'
    | '/cp/agents'
    | '/cp/audit'
    | '/cp/data'
    | '/cp/infrastructure'
    | '/cp/metering'
    | '/cp/queues'
    | '/cp/software'
    | '/cp/users'
    | '/jobs_/$jobId'
    | '/software/scripts'
    | '/workflows/$runId'
    | '/workflows/new'
    | '/cp/'
    | '/workflows/'
    | '/agents/$agentId/software'
    | '/agents/$agentId/ssh'
    | '/software/scripts/$scriptId'
    | '/software/scripts/new'
    | '/software/spack/new'
    | '/software/usecases/$usecaseId'
    | '/software/usecases/new'
    | '/software/workflow-templates/$templateId'
    | '/software/workflow-templates/new'
    | '/software/spack/$source/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  CpRoute: typeof CpRouteWithChildren
  DataMarketRoute: typeof DataMarketRoute
  FilesRoute: typeof FilesRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  SettingsRoute: typeof SettingsRoute
  SoftwareRoute: typeof SoftwareRouteWithChildren
  TerminalRoute: typeof TerminalRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  WorkflowsRunIdRoute: typeof WorkflowsRunIdRoute
  WorkflowsNewRoute: typeof WorkflowsNewRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-market': {
      id: '/data-market'
      path: '/data-market'
      fullPath: '/data-market'
      preLoaderRoute: typeof DataMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cp': {
      id: '/cp'
      path: '/cp'
      fullPath: '/cp'
      preLoaderRoute: typeof CpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cp/': {
      id: '/cp/'
      path: '/'
      fullPath: '/cp/'
      preLoaderRoute: typeof CpIndexRouteImport
      parentRoute: typeof CpRoute
    }
    '/workflows/new': {
      id: '/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$runId': {
      id: '/workflows/$runId'
      path: '/workflows/$runId'
      fullPath: '/workflows/$runId'
      preLoaderRoute: typeof WorkflowsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/scripts': {
      id: '/software/scripts'
      path: '/scripts'
      fullPath: '/software/scripts'
      preLoaderRoute: typeof SoftwareScriptsRouteImport
      parentRoute: typeof SoftwareRoute
    }
    '/jobs_/$jobId': {
      id: '/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cp/users': {
      id: '/cp/users'
      path: '/users'
      fullPath: '/cp/users'
      preLoaderRoute: typeof CpUsersRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/software': {
      id: '/cp/software'
      path: '/software'
      fullPath: '/cp/software'
      preLoaderRoute: typeof CpSoftwareRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/queues': {
      id: '/cp/queues'
      path: '/queues'
      fullPath: '/cp/queues'
      preLoaderRoute: typeof CpQueuesRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/metering': {
      id: '/cp/metering'
      path: '/metering'
      fullPath: '/cp/metering'
      preLoaderRoute: typeof CpMeteringRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/infrastructure': {
      id: '/cp/infrastructure'
      path: '/infrastructure'
      fullPath: '/cp/infrastructure'
      preLoaderRoute: typeof CpInfrastructureRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/data': {
      id: '/cp/data'
      path: '/data'
      fullPath: '/cp/data'
      preLoaderRoute: typeof CpDataRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/audit': {
      id: '/cp/audit'
      path: '/audit'
      fullPath: '/cp/audit'
      preLoaderRoute: typeof CpAuditRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/agents': {
      id: '/cp/agents'
      path: '/agents'
      fullPath: '/cp/agents'
      preLoaderRoute: typeof CpAgentsRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/agent-registration': {
      id: '/cp/agent-registration'
      path: '/agent-registration'
      fullPath: '/cp/agent-registration'
      preLoaderRoute: typeof CpAgentRegistrationRouteImport
      parentRoute: typeof CpRoute
    }
    '/cp/accounts': {
      id: '/cp/accounts'
      path: '/accounts'
      fullPath: '/cp/accounts'
      preLoaderRoute: typeof CpAccountsRouteImport
      parentRoute: typeof CpRoute
    }
    '/software/workflow-templates/new': {
      id: '/software/workflow-templates/new'
      path: '/workflow-templates/new'
      fullPath: '/software/workflow-templates/new'
      preLoaderRoute: typeof SoftwareWorkflowTemplatesNewRouteImport
      parentRoute: typeof SoftwareRoute
    }
    '/software/workflow-templates/$templateId': {
      id: '/software/workflow-templates/$templateId'
      path: '/workflow-templates/$templateId'
      fullPath: '/software/workflow-templates/$templateId'
      preLoaderRoute: typeof SoftwareWorkflowTemplatesTemplateIdRouteImport
      parentRoute: typeof SoftwareRoute
    }
    '/software/usecases/new': {
      id: '/software/usecases/new'
      path: '/usecases/new'
      fullPath: '/software/usecases/new'
      preLoaderRoute: typeof SoftwareUsecasesNewRouteImport
      parentRoute: typeof SoftwareRoute
    }
    '/software/usecases/$usecaseId': {
      id: '/software/usecases/$usecaseId'
      path: '/usecases/$usecaseId'
      fullPath: '/software/usecases/$usecaseId'
      preLoaderRoute: typeof SoftwareUsecasesUsecaseIdRouteImport
      parentRoute: typeof SoftwareRoute
    }
    '/software/spack/new': {
      id: '/software/spack/new'
      path: '/spack/new'
      fullPath: '/software/spack/new'
      preLoaderRoute: typeof SoftwareSpackNewRouteImport
      parentRoute: typeof SoftwareRoute
    }
    '/software/scripts/new': {
      id: '/software/scripts/new'
      path: '/new'
      fullPath: '/software/scripts/new'
      preLoaderRoute: typeof SoftwareScriptsNewRouteImport
      parentRoute: typeof SoftwareScriptsRoute
    }
    '/software/scripts/$scriptId': {
      id: '/software/scripts/$scriptId'
      path: '/$scriptId'
      fullPath: '/software/scripts/$scriptId'
      preLoaderRoute: typeof SoftwareScriptsScriptIdRouteImport
      parentRoute: typeof SoftwareScriptsRoute
    }
    '/agents/$agentId/ssh': {
      id: '/agents/$agentId/ssh'
      path: '/$agentId/ssh'
      fullPath: '/agents/$agentId/ssh'
      preLoaderRoute: typeof AgentsAgentIdSshRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$agentId/software': {
      id: '/agents/$agentId/software'
      path: '/$agentId/software'
      fullPath: '/agents/$agentId/software'
      preLoaderRoute: typeof AgentsAgentIdSoftwareRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/software/spack/$source/$name': {
      id: '/software/spack/$source/$name'
      path: '/spack/$source/$name'
      fullPath: '/software/spack/$source/$name'
      preLoaderRoute: typeof SoftwareSpackSourceNameRouteImport
      parentRoute: typeof SoftwareRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdSoftwareRoute: typeof AgentsAgentIdSoftwareRoute
  AgentsAgentIdSshRoute: typeof AgentsAgentIdSshRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdSoftwareRoute: AgentsAgentIdSoftwareRoute,
  AgentsAgentIdSshRoute: AgentsAgentIdSshRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface CpRouteChildren {
  CpAccountsRoute: typeof CpAccountsRoute
  CpAgentRegistrationRoute: typeof CpAgentRegistrationRoute
  CpAgentsRoute: typeof CpAgentsRoute
  CpAuditRoute: typeof CpAuditRoute
  CpDataRoute: typeof CpDataRoute
  CpInfrastructureRoute: typeof CpInfrastructureRoute
  CpMeteringRoute: typeof CpMeteringRoute
  CpQueuesRoute: typeof CpQueuesRoute
  CpSoftwareRoute: typeof CpSoftwareRoute
  CpUsersRoute: typeof CpUsersRoute
  CpIndexRoute: typeof CpIndexRoute
}

const CpRouteChildren: CpRouteChildren = {
  CpAccountsRoute: CpAccountsRoute,
  CpAgentRegistrationRoute: CpAgentRegistrationRoute,
  CpAgentsRoute: CpAgentsRoute,
  CpAuditRoute: CpAuditRoute,
  CpDataRoute: CpDataRoute,
  CpInfrastructureRoute: CpInfrastructureRoute,
  CpMeteringRoute: CpMeteringRoute,
  CpQueuesRoute: CpQueuesRoute,
  CpSoftwareRoute: CpSoftwareRoute,
  CpUsersRoute: CpUsersRoute,
  CpIndexRoute: CpIndexRoute,
}

const CpRouteWithChildren = CpRoute._addFileChildren(CpRouteChildren)

interface SoftwareScriptsRouteChildren {
  SoftwareScriptsScriptIdRoute: typeof SoftwareScriptsScriptIdRoute
  SoftwareScriptsNewRoute: typeof SoftwareScriptsNewRoute
}

const SoftwareScriptsRouteChildren: SoftwareScriptsRouteChildren = {
  SoftwareScriptsScriptIdRoute: SoftwareScriptsScriptIdRoute,
  SoftwareScriptsNewRoute: SoftwareScriptsNewRoute,
}

const SoftwareScriptsRouteWithChildren = SoftwareScriptsRoute._addFileChildren(
  SoftwareScriptsRouteChildren,
)

interface SoftwareRouteChildren {
  SoftwareScriptsRoute: typeof SoftwareScriptsRouteWithChildren
  SoftwareSpackNewRoute: typeof SoftwareSpackNewRoute
  SoftwareUsecasesUsecaseIdRoute: typeof SoftwareUsecasesUsecaseIdRoute
  SoftwareUsecasesNewRoute: typeof SoftwareUsecasesNewRoute
  SoftwareWorkflowTemplatesTemplateIdRoute: typeof SoftwareWorkflowTemplatesTemplateIdRoute
  SoftwareWorkflowTemplatesNewRoute: typeof SoftwareWorkflowTemplatesNewRoute
  SoftwareSpackSourceNameRoute: typeof SoftwareSpackSourceNameRoute
}

const SoftwareRouteChildren: SoftwareRouteChildren = {
  SoftwareScriptsRoute: SoftwareScriptsRouteWithChildren,
  SoftwareSpackNewRoute: SoftwareSpackNewRoute,
  SoftwareUsecasesUsecaseIdRoute: SoftwareUsecasesUsecaseIdRoute,
  SoftwareUsecasesNewRoute: SoftwareUsecasesNewRoute,
  SoftwareWorkflowTemplatesTemplateIdRoute:
    SoftwareWorkflowTemplatesTemplateIdRoute,
  SoftwareWorkflowTemplatesNewRoute: SoftwareWorkflowTemplatesNewRoute,
  SoftwareSpackSourceNameRoute: SoftwareSpackSourceNameRoute,
}

const SoftwareRouteWithChildren = SoftwareRoute._addFileChildren(
  SoftwareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  CpRoute: CpRouteWithChildren,
  DataMarketRoute: DataMarketRoute,
  FilesRoute: FilesRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  SettingsRoute: SettingsRoute,
  SoftwareRoute: SoftwareRouteWithChildren,
  TerminalRoute: TerminalRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  WorkflowsRunIdRoute: WorkflowsRunIdRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
