[package]
name = "kuintessence-gui"
version = "0.0.1"
description = "Kuintessence all-in-one desktop shell"
authors = ["Wang Jiaxiang <to@jiaxiang.wang>"]
license = "AGPL-3.0-only"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
