appname = casdoor
httpport = 8000
runmode = prod
copyrequestbody = true

driverName = postgres
dataSourceName = "user=casdoor password=casdoor_dev_password host=casdoor-postgres port=5432 sslmode=disable dbname=casdoor"
dbName = casdoor
showSql = false

origin = http://casdoor.localhost:15180
originFrontend =
staticBaseUrl = https://cdn.casbin.org

forceLanguage = zh
defaultLanguage = zh
defaultApplication = kuintessence-server
showGithubCorner = false

initDataNewOnly = true
initDataFile = /init_data.json
