import { join } from "node:path";

/**
 * Codegen for the in-binary SPA map. Reads a built SPA dir (`packages/web/dist`)
 * recursively and emits `packages/cli/src/gui-serve/embedded-spa.ts` with a
 * populated `EMBEDDED_SPA` map (SPA-relative path → `{ type, base64 }`).
 *
 * Only the `gui:single-binary` build runs this; it transiently overwrites the
 * committed-EMPTY module, compiles `kq` with the embedded SPA, then restores the
 * empty version (`git checkout -- …`). Run standalone with:
 *   bun run scripts/gui-embed-spa.ts [distDir]
 */

const REPO_ROOT = join(import.meta.dir, "..");
const DEFAULT_DIST = join(REPO_ROOT, "packages/web/dist");
const TARGET_MODULE = join(REPO_ROOT, "packages/cli/src/gui-serve/embedded-spa.ts");

const MIME_BY_EXT: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".wasm": "application/wasm",
};

function contentTypeFor(path: string): string {
  const dot = path.lastIndexOf(".");
  if (dot < 0) return "application/octet-stream";
  return MIME_BY_EXT[path.slice(dot).toLowerCase()] ?? "application/octet-stream";
}

/**
 * Build the `embedded-spa.ts` module source for a built SPA `distDir`. Pure +
 * exported so the codegen can be unit-tested without touching the repo tree.
 */
export async function generateEmbeddedSpaModule(distDir: string): Promise<string> {
  const map: Record<string, { type: string; base64: string }> = {};
  const glob = new Bun.Glob("**/*");
  for await (const rel of glob.scan({ cwd: distDir, onlyFiles: true })) {
    const key = rel.split("\\").join("/");
    const bytes = await Bun.file(join(distDir, rel)).arrayBuffer();
    map[key] = { type: contentTypeFor(key), base64: Buffer.from(bytes).toString("base64") };
  }

  const sorted = Object.keys(map)
    .sort()
    .reduce<typeof map>((acc, key) => {
      const entry = map[key];
      if (entry !== undefined) acc[key] = entry;
      return acc;
    }, {});

  return `// AUTO-GENERATED by scripts/gui-embed-spa.ts — do not edit by hand.
// Committed EMPTY; populated transiently only by the gui:single-binary build.
export const EMBEDDED_SPA: Record<string, { type: string; base64: string }> = ${JSON.stringify(
    sorted,
    null,
    2,
  )};
`;
}

async function main(): Promise<void> {
  const distDir = process.argv[2] ?? DEFAULT_DIST;
  if (!(await Bun.file(join(distDir, "index.html")).exists())) {
    throw new Error(
      `No built SPA at ${distDir} (missing index.html). Build it first: bun run --filter @kuintessence/web build`,
    );
  }
  const source = await generateEmbeddedSpaModule(distDir);
  await Bun.write(TARGET_MODULE, source);
  const count = (source.match(/"base64":/g) ?? []).length;
  process.stdout.write(`Wrote ${TARGET_MODULE} (${count} embedded asset(s))\n`);
}

if (import.meta.main) {
  await main();
}
