FROM rust:1.71.1-slim-bullseye as build
RUN apt update -y && apt install gcc g++ cmake apt-transport-https ca-certificates -y && apt install libssl-dev openssl pkg-config git -y
WORKDIR /app
ENV CARGO_HTTP_MULTIPLEXING=false
COPY . /app
RUN rustup component add rustfmt
RUN cargo build --bin=billing-system --release

FROM ubuntu:23.10
RUN apt update -y && apt install apt-transport-https ca-certificates -y && apt install libssl-dev openssl pkg-config -y
WORKDIR /app
# copy the build artifact from the build stage
#COPY --from=build /app/resources /app/resources
COPY --from=build /app/target/release/billing-system /app
COPY --from=build /app/config/bill-system-config.develop.yaml /app/bill-system-config.yaml
# set the startup command to run your binary
EXPOSE 80
CMD ["/app/billing-system", "bill-system-config.yaml"]
