apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels: {{- include "kq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: http
    - name: grpc
      port: {{ .Values.server.grpcPort }}
      targetPort: grpc
